### PR TITLE
edited urls (from ayush7788 to clawbhaiya)

### PR DESCRIPTION
**Pull request by uwuntudev**
So yeah edited the repo url

### CODE REVIEW

**Comment by acidicneko** [comment]
Ah thanks bro. Can plz edit the urls in bin/mm too?

**Comment by uwuntudev** [comment]
ok

**Comment by uwuntudev** [comment]
done

**Comment by uwuntudev** [comment]
Screenshot from 2021-08-30 12-47-00

lol

**Comment by acidicneko** [comment]
Thanks bro

**Comment by zghwi** [comment]
Np :)

**Comment by zghwi** [comment]
Tf

**Comment by zghwi** [comment]
I forgot that im on the windows account

**Pull request merged**
