### PR TITLE
Improve Code quality

### PR DESCRIPTION
**Pull request by wizard-28**
This PR aims to improve code quality thought the repo

### CODE REVIEW

**Comment by acidicneko** [comment]
Bro You can leave formatting :p
I just started today that's why it is bad.

**Comment by wizard-28** [comment]
Well, fixing it will bring no harm

**Comment by wizard-28** [comment]
Umm.. `git.sh` contains lot of code quality issues, take a look at it.

**Comment by wizard-28** [comment]
Other than that I've completed improving the whole repo, review it

**Pull request closed without merging**
