### PR TITLE
added if ~/.config/moon exists

### PR DESCRIPTION
**Pull request by zghwi**
image
added if ~/.config/moon exists
it works for me

### CODE REVIEW

**Comment by acidicneko** [comment]
wait bro this isn't moon in screenshot

**Comment by zghwi** [comment]
what

**Comment by acidicneko** [comment]
Yes that isn't moon

**Comment by zghwi** [comment]
wdym i don't understand

**Comment by acidicneko** [comment]
Moon doesn't has a date and time module. I am planning to add it later

**Comment by zghwi** [comment]
ik that's my own prompt

**Comment by acidicneko** [comment]
Hey are ya on discord? My id is - Ayush Yadav\#6969

**Comment by zghwi** [comment]
ok lemme add you

**Comment by zghwi** [comment]
ok i don't open discord a lot so I'm going to add you later :)

**Comment by acidicneko** [comment]
Oh okay. I was planning to make a discord server for feature requests, debug, etc

**Comment by zghwi** [comment]
oh nice why not

**Comment by zghwi** [comment]
> Hey are ya on discord? My id is - Ayush Yadav#6969

I sent a request

**Comment by zghwi** [comment]
image
we should have a fix
and I cant open discord rn

**Comment by zghwi** [comment]
image
works on [replit](https://replit.com)

**Comment by acidicneko** [comment]
OwO these missing glyphs can be fixed by installing a nerd font such as Iosevka Nerd Font

**Comment by acidicneko** [comment]
Also containers don't have battery files that's why you are getting that error. Remove battery module from moon.sh

**Comment by zghwi** [comment]
oh you cant manage terminal fonts on replit
and ok I'm going to remove it

**Pull request merged**
